# azure-pipelines-sagemaker.yml
# Triggers: manual only (no automatic run on push)
trigger: none

# Use your existing pool here.
# If you use Microsoft-hosted agents, do:
#   pool:
#     vmImage: 'ubuntu-latest'
# If you use self-hosted:
#   pool:
#     name: your_pool_name
pool:
  name: az_data_engineering2   # <--- CHANGE to whatever you currently use

# Variable group with AWS credentials + region
variables:
- group: AWS-ML-Dev            # <--- CHANGE if your group has a different name

stages:
- stage: RunSageMakerPipeline
  displayName: "Run SageMaker Pipeline"
  jobs:
  - job: RunPipeline
    displayName: "Trigger Early Crew Dispatch Pipeline"
    steps:

    # 1) Detect which Python is available and store it in $(PYTHON_CMD)
    - script: |
        echo "Detecting Python on this agent..."

        if command -v python3 >/dev/null 2>&1; then
          echo "Using python3"
          echo "##vso[task.setvariable variable=PYTHON_CMD]python3"
          python3 --version
        elif command -v python >/dev/null 2>&1; then
          echo "Using python"
          echo "##vso[task.setvariable variable=PYTHON_CMD]python"
          python --version
        else
          echo "ERROR: No Python interpreter found on PATH."
          exit 1
        fi
      displayName: "Detect Python interpreter"

    # 2) Install dependencies using the detected Python
    - script: |
        echo "Installing dependencies with $(PYTHON_CMD)..."

        $(PYTHON_CMD) -m pip install --upgrade pip
        $(PYTHON_CMD) -m pip install -r requirements39.txt
      displayName: "Install Python dependencies (requirements39.txt)"

    # 3) Export AWS creds, set PYTHONPATH, run run_pipeline.py
    - script: |
        echo "Setting AWS environment variables..."

        export AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID)
        export AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY)
        export AWS_SESSION_TOKEN=$(AWS_SESSION_TOKEN)
        export AWS_DEFAULT_REGION=$(AWS_DEFAULT_REGION)

        echo "Setting PYTHONPATH so imports work..."
        export PYTHONPATH="$PWD/early_crew_dispatch"

        echo "Running SageMaker pipeline with $(PYTHON_CMD)..."
        $(PYTHON_CMD) early_crew_dispatch/run_pipeline.py
      displayName: "Run run_pipeline.py (trigger SageMaker pipeline)"
