# azure-pipelines-sagemaker-docker.yml
trigger: none

pool:
  name: dataengineering_tf        # your self-hosted agent pool

variables:
- group:        # variable group with your AWS creds

# Expected variables in tf-sagemaker-dev:
#   AWS_ACCOUNT_ID        = <12-digit ECR account ID>  (the 3... account)
#   AWS_REGION            = us-west-2
#   AWS_ACCESS_KEY_ID     = <access key for 3... account>
#   AWS_SECRET_ACCESS_KEY = <secret key for 3... account>
#   AWS_SESSION_TOKEN     = <optional, if using STS; otherwise empty>

stages:
- stage: RunSageMakerPipeline
  displayName: "Run SageMaker Pipeline via Docker (legacy AWS CLI)"
  jobs:
  - job: RunPipeline
    displayName: "Run pipeline inside ECR-based container"
    steps:

    # Step 0: Checkout repo (latest DS code)
    - checkout: self
      displayName: "Checkout repo (latest DS code)"

    # Step 1: Debug – prove which AWS account we are using
    - script: |
        echo "=== DEBUG: AWS identity from pipeline (should be ECR account) ==="
        echo "AWS_REGION      = $(AWS_REGION)"
        echo "AWS_ACCOUNT_ID  = $(AWS_ACCOUNT_ID)"

        echo
        echo "-> sts get-caller-identity"
        aws sts get-caller-identity --region $(AWS_REGION)
      displayName: "DEBUG – who am I (should be ECR account)"
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_SESSION_TOKEN: $(AWS_SESSION_TOKEN)
        AWS_REGION: $(AWS_REGION)
        AWS_DEFAULT_REGION: $(AWS_REGION)

    # Step 2: (optional but useful) check that we can see the repo & images
    - script: |
        echo "=== DEBUG: ECR visibility from pipeline ==="

        echo "-> describe-repositories early-crew-dispatch-base"
        aws ecr describe-repositories \
          --repository-names early-crew-dispatch-base \
          --region $(AWS_REGION)

        echo
        echo "-> describe-images early-crew-dispatch-base"
        aws ecr describe-images \
          --repository-name early-crew-dispatch-base \
          --region $(AWS_REGION)
      displayName: "DEBUG – can I see the ECR repo & images?"
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_SESSION_TOKEN: $(AWS_SESSION_TOKEN)
        AWS_REGION: $(AWS_REGION)
        AWS_DEFAULT_REGION: $(AWS_REGION)

    # Step 3: Login to ECR using legacy aws ecr get-login and pull the image
    - script: |
        set -e

        echo "Logging in to ECR using legacy aws ecr get-login..."

        # 1) Call the old CLI command (supported by your AWS CLI)
        LOGIN_CMD=$(aws ecr get-login --no-include-email --region $(AWS_REGION))

        echo "aws ecr get-login returned:"
        echo "$LOGIN_CMD"

        if [ -z "$LOGIN_CMD" ]; then
          echo "ERROR: aws ecr get-login returned empty output"
          exit 1
        fi

        # 2) Extract the password that appears after -p / --password
        PASSWORD=$(echo "$LOGIN_CMD" | awk '{for (i=1;i<=NF;i++) if ($i=="-p" || $i=="--password") {print $(i+1); exit}}')

        if [ -z "$PASSWORD" ]; then
          echo "ERROR: Could not extract password from aws ecr get-login output"
          exit 1
        fi

        # 3) Non-interactive Docker login using password-stdin
        echo "$PASSWORD" | docker login --username AWS --password-stdin \
          $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com

        echo "Pulling image with dependencies..."
        docker pull $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/early-crew-dispatch-base:latest
      displayName: "Login to ECR and pull base image (legacy CLI)"
      env:
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_SESSION_TOKEN: $(AWS_SESSION_TOKEN)
        AWS_REGION: $(AWS_REGION)
        AWS_DEFAULT_REGION: $(AWS_REGION)

    # Step 4: Run container, mount repo, execute run_pipeline.py inside it
    - script: |
        set -e

        echo "Running SageMaker pipeline inside container..."

        WORKSPACE="$(System.DefaultWorkingDirectory)"

        echo "Base identity before assume-role (should be IAM user):"
        aws sts get-caller-identity

        echo ""
        echo "Assuming SageMaker execution role: $SAGEMAKER_EXECUTION_ROLE_ARN"

        # Call STS to assume the SageMaker execution role
        CREDS=$(aws sts assume-role \
          --role-arn "$SAGEMAKER_EXECUTION_ROLE_ARN" \
          --role-session-name azdo-sagemaker-pipeline \
          --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]' \
          --output text)

        # CREDS is: "AKIA... SECRET... TOKEN..."
        read ROLE_AK ROLE_SK ROLE_TOKEN <<< "$CREDS"

        export ROLE_AWS_ACCESS_KEY_ID="$ROLE_AK"
        export ROLE_AWS_SECRET_ACCESS_KEY="$ROLE_SK"
        export ROLE_AWS_SESSION_TOKEN="$ROLE_TOKEN"

        echo ""
        echo "Identity after assume-role (should be assumed-role/SageMaker-ExecutionRole-...):"
        AWS_ACCESS_KEY_ID=$ROLE_AWS_ACCESS_KEY_ID \
        AWS_SECRET_ACCESS_KEY=$ROLE_AWS_SECRET_ACCESS_KEY \
        AWS_SESSION_TOKEN=$ROLE_AWS_SESSION_TOKEN \
          aws sts get-caller-identity

        echo ""
        echo "Starting Docker container with assumed-role credentials..."

        docker run --rm \
          -e AWS_ACCESS_KEY_ID=$ROLE_AWS_ACCESS_KEY_ID \
          -e AWS_SECRET_ACCESS_KEY=$ROLE_AWS_SECRET_ACCESS_KEY \
          -e AWS_SESSION_TOKEN=$ROLE_AWS_SESSION_TOKEN \
          -e AWS_REGION=$(AWS_REGION) \
          -e AWS_DEFAULT_REGION=$(AWS_REGION) \
          -e OPENBLAS_NUM_THREADS=1 \
          -e OMP_NUM_THREADS=1 \
          -e MKL_NUM_THREADS=1 \
          -e NUMEXPR_NUM_THREADS=1 \
          -e PYTHONPATH=/workspace/early_crew_dispatch \
          -v "$WORKSPACE":/workspace \
          $(AWS_ACCOUNT_ID).dkr.ecr.$(AWS_REGION).amazonaws.com/early-crew-dispatch-base:latest \
          python early_crew_dispatch/run_pipeline.py
      displayName: "Mount repo & run run_pipeline.py in container"
      env:
        # IAM user credentials – used only to call sts:AssumeRole
        AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
        AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
        AWS_REGION: $(AWS_REGION)
        AWS_DEFAULT_REGION: $(AWS_REGION)
        # Execution role to assume
        SAGEMAKER_EXECUTION_ROLE_ARN: $(SAGEMAKER_EXECUTION_ROLE_ARN)
